package com.eslauer.models;

// Generated Apr 10, 2015 11:34:20 AM by Hibernate Tools 3.4.0.CR1

/**
 * Codes generated by hbm2java
 */
public class Codes implements java.io.Serializable {

	private Integer idcodes;
	private String icd10Code;
	private String icd10Name;
	private String icd9Code;
	private String icd9Name;

	public Codes() {
	}

	public Codes(String icd10Code, String icd10Name) {
		this.icd10Code = icd10Code;
		this.icd10Name = icd10Name;
	}

	public Codes(String icd10Code, String icd10Name, String icd9Code,
			String icd9Name) {
		this.icd10Code = icd10Code;
		this.icd10Name = icd10Name;
		this.icd9Code = icd9Code;
		this.icd9Name = icd9Name;
	}

	public Integer getIdcodes() {
		return this.idcodes;
	}

	public void setIdcodes(Integer idcodes) {
		this.idcodes = idcodes;
	}

	public String getIcd10Code() {
		return this.icd10Code;
	}

	public void setIcd10Code(String icd10Code) {
		this.icd10Code = icd10Code;
	}

	public String getIcd10Name() {
		return this.icd10Name;
	}

	public void setIcd10Name(String icd10Name) {
		this.icd10Name = icd10Name;
	}

	public String getIcd9Code() {
		return this.icd9Code;
	}

	public void setIcd9Code(String icd9Code) {
		this.icd9Code = icd9Code;
	}

	public String getIcd9Name() {
		return this.icd9Name;
	}

	public void setIcd9Name(String icd9Name) {
		this.icd9Name = icd9Name;
	}

}
