package com.eslauer.models;

// Generated Apr 10, 2015 11:34:20 AM by Hibernate Tools 3.4.0.CR1

/**
 * InsuranceRates generated by hbm2java
 */
public class InsuranceRates implements java.io.Serializable {

	private Integer idinsuranceRates;
	private int idcode;
	private int idinsurance;
	private long rate;

	public InsuranceRates() {
	}

	public InsuranceRates(int idcode, int idinsurance, long rate) {
		this.idcode = idcode;
		this.idinsurance = idinsurance;
		this.rate = rate;
	}

	public Integer getIdinsuranceRates() {
		return this.idinsuranceRates;
	}

	public void setIdinsuranceRates(Integer idinsuranceRates) {
		this.idinsuranceRates = idinsuranceRates;
	}

	public int getIdcode() {
		return this.idcode;
	}

	public void setIdcode(int idcode) {
		this.idcode = idcode;
	}

	public int getIdinsurance() {
		return this.idinsurance;
	}

	public void setIdinsurance(int idinsurance) {
		this.idinsurance = idinsurance;
	}

	public long getRate() {
		return this.rate;
	}

	public void setRate(long rate) {
		this.rate = rate;
	}

}
