package com.eslauer.models;

// Generated Apr 10, 2015 11:34:20 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Patient generated by hbm2java
 */
public class Patient implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	
	private Integer idpatient;
	private String firstName;
	private String lastName;
	private Date dob;
	private String gender;
	private Date lastUpdated;
	private String cell;
	private int idinsurance;

	public Patient() {
	}

	public Patient(String firstName, String lastName, Date dob, String gender,
			String cell, int idinsurance) {
		this.firstName = firstName;
		this.lastName = lastName;
		this.dob = dob;
		this.gender = gender;
		this.cell = cell;
		this.idinsurance = idinsurance;
	}

	public Patient(String firstName, String lastName, Date dob, String gender,
			Date lastUpdated, String cell, int idinsurance) {
		this.firstName = firstName;
		this.lastName = lastName;
		this.dob = dob;
		this.gender = gender;
		this.lastUpdated = lastUpdated;
		this.cell = cell;
		this.idinsurance = idinsurance;
	}

	public Integer getIdpatient() {
		return this.idpatient;
	}

	public void setIdpatient(Integer idpatient) {
		this.idpatient = idpatient;
	}

	public String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	public String getLastName() {
		return this.lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	public Date getDob() {
		return this.dob;
	}

	public void setDob(Date dob) {
		this.dob = dob;
	}

	public String getGender() {
		return this.gender;
	}

	public void setGender(String gender) {
		this.gender = gender;
	}

	public Date getLastUpdated() {
		return this.lastUpdated;
	}

	public void setLastUpdated(Date lastUpdated) {
		this.lastUpdated = lastUpdated;
	}

	public String getCell() {
		return this.cell;
	}

	public void setCell(String cell) {
		this.cell = cell;
	}

	public int getIdinsurance() {
		return this.idinsurance;
	}

	public void setIdinsurance(int idinsurance) {
		this.idinsurance = idinsurance;
	}

}
