package com.eslauer.models;

// Generated Apr 10, 2015 11:34:20 AM by Hibernate Tools 3.4.0.CR1

/**
 * Procedure generated by hbm2java
 */
public class Procedure implements java.io.Serializable {

	private Integer idprocedure;
	private String name;
	private int idcode;
	private int idpatient;

	public Procedure() {
	}

	public Procedure(String name, int idcode, int idpatient) {
		this.name = name;
		this.idcode = idcode;
		this.idpatient = idpatient;
	}

	public Integer getIdprocedure() {
		return this.idprocedure;
	}

	public void setIdprocedure(Integer idprocedure) {
		this.idprocedure = idprocedure;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public int getIdcode() {
		return this.idcode;
	}

	public void setIdcode(int idcode) {
		this.idcode = idcode;
	}

	public int getIdpatient() {
		return this.idpatient;
	}

	public void setIdpatient(int idpatient) {
		this.idpatient = idpatient;
	}

}
