package com.eslauer.models;

// Generated Apr 10, 2015 11:34:20 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Schedule generated by hbm2java
 */
public class Schedule implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	
	private Integer idschedule;
	private Date appointmentDateTime;
	private int idpatient;

	public Schedule() {
	}

	public Schedule(Date appointmentDateTime, int idpatient) {
		this.appointmentDateTime = appointmentDateTime;
		this.idpatient = idpatient;
	}

	public Integer getIdschedule() {
		return this.idschedule;
	}

	public void setIdschedule(Integer idschedule) {
		this.idschedule = idschedule;
	}

	public Date getAppointmentDateTime() {
		return this.appointmentDateTime;
	}

	public void setAppointmentDateTime(Date appointmentDateTime) {
		this.appointmentDateTime = appointmentDateTime;
	}

	public int getIdpatient() {
		return this.idpatient;
	}

	public void setIdpatient(int idpatient) {
		this.idpatient = idpatient;
	}

}
